[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; Needed for LittleFS upload via "Upload File System Image"
board_build.filesystem = littlefs

; WebServer + LittleFS are in core. No extra libs required.
; If you switch to AsyncWebServer later, add lib_deps here.
